apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-e6data
  labels:
    app: flask-e6data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-e6data
  template:
    metadata:
      labels:
        app: flask-e6data
    spec:
      containers:
      - name: flask-e6data
        image: 277707103654.dkr.ecr.ap-south-1.amazonaws.com/e6data:latest
        ports:
        - containerPort: 8080
